# Generated by Django 4.2.9 on 2024-01-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='imagen',
        ),
    ]
