# Generated by Django 4.2.9 on 2024-01-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0002_alter_especie_especie_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raza',
            name='raza_mascota',
            field=models.CharField(choices=[('Pitbull', 'Pitbull'), ('Labrador Retriever', 'Labrador Retriever'), ('Pastor Alemán', 'Pastor Alemán'), ('Bulldog Francés', 'Bulldog Francés'), ('Golden Retriever', 'Golden Retriever'), ('Dachshund', 'Dachshund'), ('Chihuahua', 'Chihuahua'), ('Boxer', 'Boxer'), ('Rottweiler', 'Rottweiler'), ('Bulldog Inglés', 'Bulldog Inglés'), ('Shih Tzu', 'Shih Tzu'), ('Doberman', 'Doberman'), ('Husky Siberiano', 'Husky Siberiano'), ('Pomerania', 'Pomerania'), ('Bichón Frisé', 'Bichón Frisé'), ('Schnauzer', 'Schnauzer'), ('Cocker Spaniel', 'Cocker Spaniel'), ('Gato Persa', 'Gato Persa'), ('Siames', 'Siames'), ('Maine Coon', 'Maine Coon'), ('Bengalí', 'Bengalí'), ('Sphynx', 'Sphynx'), ('Ragdoll', 'Ragdoll')], max_length=100),
        ),
    ]
