# Generated by Django 4.2.9 on 2024-01-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0002_propietario_direccion_propietario_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
