# Generated by Django 4.2.9 on 2024-01-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0002_remove_mascota_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='experiencia',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
