# Generated by Django 4.2.9 on 2024-01-12 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0003_propietario_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_servicio', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.cuidador')),
            ],
        ),
    ]
