# Generated by Django 4.2.9 on 2024-01-23 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0004_alter_especie_especie_mascota_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id_tipo_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_servicio', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.tiposervicio'),
        ),
    ]
