# Generated by Django 4.2.9 on 2024-01-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0004_alter_servicio_descripcion_alter_servicio_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
