# Generated by Django 4.2.9 on 2024-01-13 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0004_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mascota', models.CharField(max_length=100)),
                ('tipo_mascota', models.CharField(max_length=50)),
                ('tamaño_mascota', models.CharField(max_length=50)),
                ('raza_mascota', models.CharField(max_length=50)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
