# Generated by Django 4.2.9 on 2024-01-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0005_alter_servicio_tipo_servicio_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='raza_mascota',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
