# Generated by Django 4.2.9 on 2024-01-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0005_tiposervicio_alter_servicio_tipo_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='especie_mascota',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='raza',
            name='raza_mascota',
            field=models.CharField(max_length=100),
        ),
    ]
