# Generated by Django 4.2.9 on 2024-01-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0006_alter_mascota_raza_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imgprod'),
        ),
    ]
