# Generated by Django 4.2.9 on 2024-01-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0006_alter_especie_especie_mascota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='pelaje',
            field=models.CharField(choices=[('Duro', 'Duro'), ('Rizado', 'Rizado'), ('Corto', 'Corto'), ('Largo', 'Largo'), ('Sin pelo', 'Sin pelo')], max_length=30),
        ),
    ]
