# Generated by Django 4.2.9 on 2024-01-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0007_alter_mascota_pelaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='especializacion',
            field=models.CharField(choices=[('Perros', 'Perros'), ('Perros pequeños', 'Perros pequeños'), ('Perros grandes', 'Perros grandes'), ('Gatos', 'Gatos'), ('Perros y Gatos', 'Perros y Gatos')], default='', max_length=50),
        ),
    ]
