# Generated by Django 4.2.9 on 2024-01-13 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0007_mascota_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('id_prestacion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_mascotas', models.IntegerField(default=1)),
                ('mascota', models.ManyToManyField(to='app_mascotas.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='DetPrestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(default=django.utils.timezone.now)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('id_cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.cuidador')),
                ('id_prestacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.prestacion')),
                ('id_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.servicio')),
            ],
        ),
    ]
