# Generated by Django 4.2.9 on 2024-01-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0008_alter_cuidador_especializacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imgprod'),
        ),
    ]
