# Generated by Django 4.2.9 on 2024-01-13 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0008_prestacion_detprestacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detprestacion',
            name='id_prestacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.prestacion'),
        ),
    ]
