# Generated by Django 4.2.9 on 2024-01-14 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0009_alter_detprestacion_id_prestacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestacion',
            name='mascota',
        ),
        migrations.AddField(
            model_name='detprestacion',
            name='id_mascota',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.mascota'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detprestacion',
            name='id_prestacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.prestacion'),
        ),
    ]
