# Generated by Django 4.2.9 on 2024-01-23 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0009_alter_propietario_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='id_especie',
        ),
        migrations.AddField(
            model_name='raza',
            name='id_especie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.especie'),
            preserve_default=False,
        ),
    ]
