# Generated by Django 4.2.9 on 2024-01-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0010_remove_mascota_id_especie_raza_id_especie'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
    ]
