# Generated by Django 4.2.9 on 2024-01-14 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0010_remove_prestacion_mascota_detprestacion_id_mascota_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detprestacion',
            name='estado',
        ),
        migrations.AddField(
            model_name='prestacion',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='prestacion',
            name='id_propietario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
