# Generated by Django 4.2.9 on 2024-01-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0011_mascota_es_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
    ]
