# Generated by Django 4.2.9 on 2024-01-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0011_remove_detprestacion_estado_prestacion_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detprestacion',
            name='id_prestacion',
        ),
        migrations.AddField(
            model_name='detprestacion',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.DeleteModel(
            name='Prestacion',
        ),
    ]
