# Generated by Django 4.2.9 on 2024-01-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0012_remove_detprestacion_id_prestacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detprestacion',
            old_name='fecha_fin',
            new_name='fecha_prestacion',
        ),
        migrations.RemoveField(
            model_name='detprestacion',
            name='fecha_inicio',
        ),
        migrations.AlterField(
            model_name='detprestacion',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
