# Generated by Django 4.2.9 on 2024-01-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0013_rename_fecha_fin_detprestacion_fecha_prestacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuidador',
            name='disponibilidad',
            field=models.CharField(default='Disponible', max_length=50),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='experiencia',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='especializacion',
            field=models.CharField(default='', max_length=50),
        ),
    ]
