# Generated by Django 4.2.9 on 2024-01-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0015_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Mensaje',
        ),
    ]
