# Generated by Django 4.2.9 on 2024-01-17 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0017_alter_mensaje_destinatario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensaje_recibido', to=settings.AUTH_USER_MODEL),
        ),
    ]
