# Generated by Django 4.2.9 on 2024-01-17 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0018_alter_mensaje_destinatario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='contenido',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='fecha',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='fue_leido',
            new_name='is_read',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='remitente',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='usuario',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='recipient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensaje',
            name='sender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages_as_sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensaje',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
